# (Opcional) Adiciona tags com o nome da aplicação para os gráficos
spring.application.name=poc-agenda-dashboard

# Permite que o Tomcat aceite conexões de fora do localhost (ex: rede do Docker)
server.address=0.0.0.0

# ---------------------------------------------------------
# MONGODB (O Read Store)
# ---------------------------------------------------------
spring.mongodb.uri=mongodb://admin:adminpassword@localhost:27017/dashboard_db?authSource=admin

# Desserializadores para interpretar a mensagem que vem da API
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# A API principal roda na 8080, e o Kafka UI na 8081.
# O nosso microsserviço vai rodar na 8082 para não dar conflito.
server.port=8082

# Configuração de Mensageria (Local vs Cloud)
spring.kafka.bootstrap-servers=${KAFKA_SERVER:localhost:9092}

# Dinamismo de Segurança: O fallback padrão é PLAINTEXT (para o Docker local)
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=PLAIN

# Adicionamos os fallbacks (:local) para não estourar erro no console
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
username="${KAFKA_USER:local}" \
password="${KAFKA_PASSWORD:local}";

# Identificação do Consumidor (Apenas no Dashboard)
# O Kafka usa isso para não mandar a mesma mensagem duas vezes para a mesma aplicação.
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:agenda-dashboard-group}

# Se o microsserviço cair, ao voltar, ele lê tudo o que perdeu desde a última vez
spring.kafka.consumer.auto-offset-reset=earliest

# Tópicos
app.kafka.topic.contact-events=${KAFKA_TOPIC:contact-events}

# Libera os endpoints de health, info e prometheus para acesso web
management.endpoints.web.exposure.include=health,info,prometheus

# (Opcional) Garante a exportação das métricas no novo padrão do Spring Boot 3
management.prometheus.metrics.export.enabled=true

# Força o Micrometer a enviar o nome da aplicação como uma tag reconhecida pelo Grafana
management.metrics.tags.application=${spring.application.name}