# A API principal roda na 8080, e o Kafka UI na 8081.
# Nosso microsserviço vai rodar na 8082 para não dar conflito.
server.port=8082
spring.application.name=poc-agenda-dashboard

# Configuração de Mensageria (Local vs Cloud)
spring.kafka.bootstrap-servers=${KAFKA_SERVER:localhost:9092}

# Dinamismo de Segurança: O fallback padrão é PLAINTEXT (para o Docker local)
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=PLAIN

# Adicionamos os fallbacks (:local) para não estourar erro no console
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
username="${KAFKA_USER:local}" \
password="${KAFKA_PASSWORD:local}";

# Identificação do Consumidor (Apenas no Dashboard)
# O Kafka usa isso para não mandar a mesma mensagem duas vezes para a mesma aplicação.
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:agenda-dashboard-group}

# Se o microsserviço cair, ao voltar, ele lê tudo o que perdeu desde a última vez
spring.kafka.consumer.auto-offset-reset=earliest

# Tópicos
app.kafka.topic.contact-created=${KAFKA_TOPIC:contact-created}
app.kafka.topic.contact-deleted=${KAFKA_TOPIC_DELETED:contact-deleted}