# A API principal roda na 8080, e o Kafka UI na 8081.
# Nosso microsserviço vai rodar na 8082 para não dar conflito.
server.port=8082
spring.application.name=poc-agenda-dashboard

# Configuração de Mensageria Cloud - Confluent
spring.kafka.bootstrap-servers=${KAFKA_SERVER}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
username="${KAFKA_USER}" \
password="${KAFKA_PASSWORD}";

# Identificação do Consumidor (Apenas no Dashboard)

# O "Consumer Group" identifica quem está lendo a mensagem.
# O Kafka usa isso para não mandar a mesma mensagem duas vezes para a mesma aplicação.
spring.kafka.consumer.group-id=agenda-dashboard-group

# Se o microsserviço cair, ao voltar, ele lê tudo o que perdeu desde a última vez
spring.kafka.consumer.auto-offset-reset=earliest